services:
  - type: web
    name: ipo-reader-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    workingDirectory: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
